title: DynAPI
description: Dynamic API for (postgresql) Databases
theme: just-the-docs
#remote_theme: just-the-docs/just-the-docs@v0.4.2

baseurl: "/docs" # the subpath of your site, e.g. /blog

permalink: pretty

color_scheme: dark

# Set a path/url to a logo that will be displayed instead of the title
logo: "/assets/DynAPI.svg"
# Set a path/url to a favicon that will be displayed by the browser
favicon_ico: "/assets/favicon.ico"

enable_copy_code_button: true
search_enabled: true
heading_anchors: true


back_to_top: true
back_to_top_text: "Back to top"

footer_content: "Copyright &copy; 2023 DynAPI"

# Footer last edited timestamp
#last_edit_timestamp: true # show or hide edit time - page must have `last_modified_date` defined in the frontmatter
#last_edit_time_format: "%b %e %Y at %I:%M %p" # uses ruby's time format: https://ruby-doc.org/stdlib-2.7.0/libdoc/time/rdoc/Time.html

mermaid:
  # Version of mermaid library
  # Pick an available version from https://cdn.jsdelivr.net/npm/mermaid/
  version: "9.1.3"

callouts_level: quiet # or loud
callouts:
  highlight:
    color: blue
  important:
    title: Important
    color: yellow
  new:
    title: New
    color: green
  note:
    title: Note
    color: yellow
  warning:
    title: Warning
    color: red

kramdown:
  syntax_highlighter_opts:
    block:
      line_numbers: false

compress_html:
  clippings: all
  comments: all
  endings: all
  startings: []
  blanklines: false
  profile: false
  # ignore:
  #   envs: all
